package igentuman.bfr.common;

import igentuman.bfr.client.BfrBlockStateProvider;
import igentuman.bfr.client.BfrItemModelProvider;
import igentuman.bfr.client.BfrLangProvider;
import igentuman.bfr.client.GeneratorsSoundProvider;
import igentuman.bfr.common.loot.GeneratorsLootProvider;
import net.minecraft.data.DataGenerator;
import net.minecraftforge.common.data.ExistingFileHelper;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod.EventBusSubscriber;
import net.minecraftforge.fml.common.Mod.EventBusSubscriber.Bus;
import net.minecraftforge.fml.event.lifecycle.GatherDataEvent;

@EventBusSubscriber(modid = MekanismGenerators.MODID, bus = Bus.MOD)
public class BfrDataGenerator {

    private BfrDataGenerator() {
    }

    @SubscribeEvent
    public static void gatherData(GatherDataEvent event) {
        DataGenerator gen = event.getGenerator();
        ExistingFileHelper existingFileHelper = event.getExistingFileHelper();
        if (event.includeClient()) {
            //Client side data generators
            gen.addProvider(new BfrLangProvider(gen));
            gen.addProvider(new GeneratorsSoundProvider(gen, existingFileHelper));
            //Let the blockstate provider see models generated by the item model provider
            BfrItemModelProvider itemModelProvider = new BfrItemModelProvider(gen, existingFileHelper);
            gen.addProvider(itemModelProvider);
            gen.addProvider(new BfrBlockStateProvider(gen, itemModelProvider.existingFileHelper));
        }
        if (event.includeServer()) {
            //Server side data generators
            gen.addProvider(new BfrTagProvider(gen, existingFileHelper));
            gen.addProvider(new GeneratorsLootProvider(gen));
            gen.addProvider(new BfrRecipeProvider(gen, existingFileHelper));
        }
    }
}