import java.util.function.Consumer

plugins {
    id('java')
    id('idea')
    id('net.neoforged.moddev') version('2.0.88')
}

tasks.named('wrapper', Wrapper) {
    //Define wrapper values here so as to not have to always do so when updating gradlew.properties
    gradleVersion = '8.14.1'
    distributionType = Wrapper.DistributionType.ALL
}

tasks.named('updateDaemonJvm', UpdateDaemonJvm) {
    languageVersion = JavaLanguageVersion.of("${java_version}")
}

defaultTasks('build')

group = "igentuman.bfr"
version = "${minecraft_version}-${mod_version}"
project.base.archivesName = "BetterFusionReactor"

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of("${java_version}"))
        vendor.set(JvmVendorSpec.JETBRAINS)
    }
    withSourcesJar()
}
final runsFolder = layout.projectDirectory.dir('runs')
sourceSets.main.resources { srcDir 'src/generated/resources' }

neoForge {
    version = neo_version

    mods {
        bfr {
            sourceSet(sourceSets.main)
        }
    }
    
    // Access transformers if needed
    if (file('src/main/resources/META-INF/accesstransformer.cfg').exists()) {
        accessTransformers.from(file('src/main/resources/META-INF/accesstransformer.cfg'))
    }
    
    runs {
        client {
            client()
            gameDirectory.value(runsFolder.dir('run'))
            sourceSet = sourceSets.main
        }

        server {
            gameDirectory.value(runsFolder.dir('server'))
            server()
            sourceSet = sourceSets.main
        }

        data {
            data()
            gameDirectory.value(runsFolder.dir('data'))
            programArguments.addAll('--all', '--output', file('src/datagen/generated/').absolutePath,
                    '--mod', 'bfr', '--existing', file('src/main/resources/').absolutePath)
            sourceSet = sourceSets.main
        }
    }
}

static void exclusiveRepo(RepositoryHandler handler, String url, String... groups) {
    exclusiveRepo(handler, url, filter -> {
        for (def group : groups) {
            filter.includeGroup(group)
        }
    })
}

static void exclusiveRepo(RepositoryHandler handler, String url, Consumer<InclusiveRepositoryContentDescriptor> filterSetup) {
    handler.exclusiveContent {
        it.forRepositories(handler.maven {
            setUrl(url)
        })
        it.filter { f -> filterSetup.accept(f) }
    }
}

repositories { RepositoryHandler handler ->
    exclusiveRepo(handler, 'https://maven.blamejared.com', filter -> {
        filter.includeGroupAndSubgroups('com.blamejared')
        filter.includeGroup('mezz.jei')
        filter.includeGroup('org.openzen.zencode')
    })
    exclusiveRepo(handler, 'https://maven.terraformersmc.com/', 'dev.emi')
    exclusiveRepo(handler, 'https://maven.theillusivec4.top/', 'top.theillusivec4.curios')
    exclusiveRepo(handler, 'https://maven.tterrag.com/', 'team.chisel.ctm')
    exclusiveRepo(handler, 'https://squiddev.cc/maven/', 'cc.tweaked', 'org.squiddev')
    exclusiveRepo(handler, 'https://dogforce-games.com/maven/', 'dev.gigaherz.jsonthings')
    exclusiveRepo(handler, 'https://maven2.bai.lol', 'lol.bai', 'mcp.mobius.waila')//WTHIT
    exclusiveRepo(handler, 'https://www.cursemaven.com', 'curse.maven')
    exclusiveRepo(handler, 'https://modmaven.dev/', 'mcjty.theoneprobe', 'dev.technici4n', 'mekanism', 'mekanism.generators')
    exclusiveRepo(handler, 'https://maven.minecraftforge.net/releases/', 'com.github.glitchfiend')
    exclusiveRepo(handler, 'https://maven.thiakil.com', 'com.thiakil', 'moze_intel.projecte')
    exclusiveRepo(handler, 'https://maven.parchmentmc.org/', 'org.parchmentmc.data')
    handler.exclusiveContent {
        it.forRepositories(handler.mavenCentral())
        it.filter {
            includeGroup('org.appliedenergistics')
        }
    }
}

dependencies {
    compileOnly(project(':annotation-processor'))
    annotationProcessor(project(':annotation-processor'))
    compileOnly("dev.emi:emi-neoforge:${emi_version}+${minecraft_version}:api")
    // JEI
    compileOnly("mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}")
    if (recipe_viewer == 'jei' || recipe_viewer == 'hybrid') {
        runtimeOnly("mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}")
    }
    
    // Mekanism
    implementation("mekanism:Mekanism:${mekanism_version}")// core
    implementation("mekanism:Mekanism:${mekanism_version}:generators")// Mekanism: Generators
    
    // Other dependencies
    compileOnly("cc.tweaked:cc-tweaked-${previous_minor_minecraft_version}-forge-api:${cc_tweaked_version}")
    compileOnly("curse.maven:opencomputers2-437654:${oc2_id}")
}

jar {
    manifest {
        attributes([
                "Specification-Title"     : "bfr",
                "Specification-Vendor"    : "igentuman",
                "Specification-Version"   : "${project.mod_version}", // We are version 1 of ourselves
                "Implementation-Title"    : project.name,
                "Implementation-Version"  : "${project.mod_version}",
                "Implementation-Vendor"   : "igentuman",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

tasks.withType(JavaCompile).configureEach({
    it.options.encoding = 'UTF-8'
})

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version_range      : neo_version_range,
            neo_version            : neo_version,
            loader_version_range   : loader_version_range,
            generators_version     : generators_version,
            mod_id                 : 'bfr',
            mod_name               : 'Better Fusion Reactor',
            mod_license            : 'MIT',
            mod_version            : mod_version,
            mod_authors            : 'igentuman',
            mod_description        : 'BFR'
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}
sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}